/*
 * SPDX-License-Identifier: MIT
 * Copyright 2023, Artem Savkov
 */

#include "include/rp2040-oled.h"

const uint8_t scan_addrs[] = {0x3c, 0x3d};

const uint8_t oled128_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_DISPLAY_STARTLINE, 0x00,
        OLED_CMD_SET_CONTRAST, 0x40,
        OLED_CMD_SET_SEGMENT_REMAP_REVERSE, 0xc8,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x7f,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x50,
        OLED_CMD_SET_PRECHARGE_PERIOD, 0x22,
        OLED_CMD_SET_VCOM_DESELECT_LEVEL, 0x35,
        OLED_CMD_SET_PAGE_ADDR | 0x00,
        OLED_CMD_SET_COM_PINS, 0x12,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_DISPLAY_ON};

const uint8_t oled64x128_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x51,
        OLED_CMD_SET_ADDR_PAGE,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x3f,
        OLED_CMD_SET_DISPLAY_STARTLINE, 0x00,
        OLED_CMD_SET_DISPLAY_OFFSET, 0x60,
        OLED_CMD_SET_DC_DC, 0x80,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_SEGMENT_REMAP_NORMAL, 0xc0,
        OLED_CMD_SET_CONTRAST, 0x40,
        OLED_CMD_SET_PRECHARGE_PERIOD, 0x22,
        OLED_CMD_SET_VCOM_DESELECT_LEVEL, 0x35,
        OLED_CMD_DISPLAY_ON};

const uint8_t oled132_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_LC_ADDR | 0x02,
        OLED_CMD_SET_HC_ADDR | 0x00,
        OLED_CMD_SET_DISPLAY_STARTLINE0,
        OLED_CMD_SET_CONTRAST, 0xa0,
        OLED_CMD_SET_SCAN_DIR_NORMAL,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x3f,
        OLED_CMD_SET_DISPLAY_OFFSET, 0x00,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x80,
        OLED_CMD_SET_PRECHARGE_PERIOD, 0xf1,
        OLED_CMD_SET_COM_PINS, 0x12,
        OLED_CMD_SET_VCOM_DESELECT_LEVEL, 0x40,
        OLED_CMD_SET_SSD1306_ADDR_MODE, 0x02,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_DISPLAY_NORMAL};

const uint8_t oled64_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x3f,
        OLED_CMD_SET_DISPLAY_OFFSET, 0x00,
        OLED_CMD_SET_DISPLAY_STARTLINE0,
        OLED_CMD_SET_SEGMENT_REMAP_REVERSE, 0xc8,
        OLED_CMD_SET_COM_PINS, 0x12,
        OLED_CMD_SET_CONTRAST, 0xff,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x80,
        OLED_CMD_SET_CHARGE_PUMP, 0x14,
        OLED_CMD_DISPLAY_ON,
        OLED_CMD_SET_SSD1306_ADDR_MODE, 0x02};

const uint8_t oled32_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x80,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x1f,
        OLED_CMD_SET_DISPLAY_OFFSET, 0x00,
        OLED_CMD_SET_DISPLAY_STARTLINE0,
        OLED_CMD_SET_CHARGE_PUMP, 0x14,
        OLED_CMD_SET_SEGMENT_REMAP_REVERSE, 0xc8,
        OLED_CMD_SET_COM_PINS, 0x02,
        OLED_CMD_SET_CONTRAST, 0x7f,
        OLED_CMD_SET_PRECHARGE_PERIOD, 0xf1,
        OLED_CMD_SET_VCOM_DESELECT_LEVEL, 0x40,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_DISPLAY_ON};

const uint8_t oled72_initbuf[] = {
        0x00,
        OLED_CMD_DISPLAY_OFF,
        OLED_CMD_SET_MULTIPLEX_RATIO, 0x3f,
        OLED_CMD_SET_DISPLAY_OFFSET, 0x00,
        OLED_CMD_SET_DISPLAY_STARTLINE0,
        OLED_CMD_SET_SEGMENT_REMAP_REVERSE, 0xc8,
        OLED_CMD_SET_COM_PINS, 0x12,
        OLED_CMD_SET_CONTRAST, 0xff,
        OLED_CMD_SET_DC_DC, 0x30,
        OLED_CMD_SET_PRECHARGE_PERIOD, 0xf1,
        OLED_CMD_SET_DISPLAY_RAM,
        OLED_CMD_SET_DISPLAY_NORMAL,
        OLED_CMD_SET_DISPLAY_CLOCK, 0x80,
        OLED_CMD_SET_CHARGE_PUMP, 0x14,
        OLED_CMD_DISPLAY_ON,
        OLED_CMD_SET_SSD1306_ADDR_MODE, 0x02};
